## Examining design matrices in Python

In [1]:
import numpy as np
import statsmodels.api as sm
from patsy import dmatrices

Let's use the tips database.

In [2]:
tips = sm.datasets.get_rdataset('tips','reshape2',cache=True).data

In [3]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


Now we'll create and examine the design matrices using patsy (yes, I know it's deprecated, but I'll stop using it as soon as statsmodels does).

In [4]:
y,X = dmatrices('tip ~ total_bill',data=tips)

In [5]:
X

DesignMatrix with shape (244, 2)
  Intercept  total_bill
          1       16.99
          1       10.34
          1       21.01
          1       23.68
          1       24.59
          1       25.29
          1        8.77
          1       26.88
          1       15.04
          1       14.78
          1       10.27
          1       35.26
          1       15.42
          1       18.43
          1       14.83
          1       21.58
          1       10.33
          1       16.29
          1       16.97
          1       20.65
          1       17.92
          1       20.29
          1       15.77
          1       39.42
          1       19.82
          1       17.81
          1       13.37
          1       12.69
          1       21.70
          1       19.65
  [214 rows omitted]
  Terms:
    'Intercept' (column 0)
    'total_bill' (column 1)
  (to view full data, use np.asarray(this_obj))

In [6]:
y

DesignMatrix with shape (244, 1)
   tip
  1.01
  1.66
  3.50
  3.31
  3.61
  4.71
  2.00
  3.12
  1.96
  3.23
  1.71
  5.00
  1.57
  3.00
  3.02
  3.92
  1.67
  3.71
  3.50
  3.35
  4.08
  2.75
  2.23
  7.58
  3.18
  2.34
  2.00
  2.00
  4.30
  3.00
  [214 rows omitted]
  Terms:
    'tip' (column 0)
  (to view full data, use np.asarray(this_obj))

Estimate the parameters using the classic matrix calculation:

$$\beta = (X^{T} X)^{-1} X^{T} y$$

In [7]:
from numpy.linalg import inv
β = inv(X.T @ X) @ X.T @ y
β

array([[0.92026961],
       [0.10502452]])

Calculate the fitted values:

$$\hat{y} = X\beta$$

In [8]:
ŷ = X @ β
ŷ

array([[2.70463616],
       [2.00622312],
       [3.12683472],
       [3.40725019],
       [3.5028225 ],
       [3.57633966],
       [1.84133463],
       [3.74332864],
       [2.49983836],
       [2.47253198],
       [1.99887141],
       [4.6234341 ],
       [2.53974767],
       [2.85587147],
       [2.47778321],
       [3.1866987 ],
       [2.00517288],
       [2.631119  ],
       [2.70253567],
       [3.0890259 ],
       [2.80230897],
       [3.05121707],
       [2.57650625],
       [5.06033609],
       [3.00185555],
       [2.79075627],
       [2.32444741],
       [2.25303074],
       [3.19930164],
       [2.98400138],
       [1.92325375],
       [2.84746951],
       [2.50193885],
       [3.09322688],
       [2.78760553],
       [3.4471595 ],
       [2.63321949],
       [2.69833469],
       [2.88317784],
       [4.20438627],
       [2.60486287],
       [2.75399769],
       [2.38431139],
       [1.93690694],
       [4.11301494],
       [2.84116804],
       [3.25496464],
       [4.323

Now we'll compute the residual or error term,  which, as usual, is the difference between the original y values and the fitted values:
$$e = y - \hat{y}$$

In [9]:
e = y - ŷ

The original y values are the fitted values plus the error term,:

$$ y = \hat{y} + e = Xβ + e $$

In [10]:
    X @ β + e

array([[ 1.01],
       [ 1.66],
       [ 3.5 ],
       [ 3.31],
       [ 3.61],
       [ 4.71],
       [ 2.  ],
       [ 3.12],
       [ 1.96],
       [ 3.23],
       [ 1.71],
       [ 5.  ],
       [ 1.57],
       [ 3.  ],
       [ 3.02],
       [ 3.92],
       [ 1.67],
       [ 3.71],
       [ 3.5 ],
       [ 3.35],
       [ 4.08],
       [ 2.75],
       [ 2.23],
       [ 7.58],
       [ 3.18],
       [ 2.34],
       [ 2.  ],
       [ 2.  ],
       [ 4.3 ],
       [ 3.  ],
       [ 1.45],
       [ 2.5 ],
       [ 3.  ],
       [ 2.45],
       [ 3.27],
       [ 3.6 ],
       [ 2.  ],
       [ 3.07],
       [ 2.31],
       [ 5.  ],
       [ 2.24],
       [ 2.54],
       [ 3.06],
       [ 1.32],
       [ 5.6 ],
       [ 3.  ],
       [ 5.  ],
       [ 6.  ],
       [ 2.05],
       [ 3.  ],
       [ 2.5 ],
       [ 2.6 ],
       [ 5.2 ],
       [ 1.56],
       [ 4.34],
       [ 3.51],
       [ 3.  ],
       [ 1.5 ],
       [ 1.76],
       [ 6.73],
       [ 3.21],
       [ 2.  ],
       [

In [11]:
y

DesignMatrix with shape (244, 1)
   tip
  1.01
  1.66
  3.50
  3.31
  3.61
  4.71
  2.00
  3.12
  1.96
  3.23
  1.71
  5.00
  1.57
  3.00
  3.02
  3.92
  1.67
  3.71
  3.50
  3.35
  4.08
  2.75
  2.23
  7.58
  3.18
  2.34
  2.00
  2.00
  4.30
  3.00
  [214 rows omitted]
  Terms:
    'tip' (column 0)
  (to view full data, use np.asarray(this_obj))

Let's compare to the output from statsmodels OLS.

In [12]:
import statsmodels.formula.api as smf

In [13]:
results = smf.ols('tip ~ total_bill',data=tips).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.457
Model:                            OLS   Adj. R-squared:                  0.454
Method:                 Least Squares   F-statistic:                     203.4
Date:                Mon, 06 Jul 2026   Prob (F-statistic):           6.69e-34
Time:                        12:20:14   Log-Likelihood:                -350.54
No. Observations:                 244   AIC:                             705.1
Df Residuals:                     242   BIC:                             712.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9203      0.160      5.761      0.000       0.606       1.235
total_bill     0.1050      0.007     14.260      0.000       0.091       0.120
==============================================================================
Omnibus:                       20.185   Durbin-Watson:                   2.151
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               37.750
Skew:                           0.443   Prob(JB):                     6.35e-09
Kurtosis:                       4.711   Cond. No.                         53.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [14]:
results.params

Intercept     0.920270
total_bill    0.105025
dtype: float64

In [15]:
results.fittedvalues

0      2.704636
1      2.006223
2      3.126835
3      3.407250
4      3.502822
         ...   
239    3.969131
240    3.774836
241    3.301175
242    2.791807
243    2.892630
Length: 244, dtype: float64

In [16]:
results.resid

0     -1.694636
1     -0.346223
2      0.373165
3     -0.097250
4      0.107178
         ...   
239    1.950869
240   -1.774836
241   -1.301175
242   -1.041807
243    0.107370
Length: 244, dtype: float64

In [18]:
results.fittedvalues + results.resid

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Length: 244, dtype: float64

statsmodels is obviously more practical for applied analysis, despite the relative ease of matrix computations with Python.